info:
  name: ${project.name}
  version: ${project.version}
  description: ${project.description}

spring:
  application:
    name: zuul-gateway

logging:
  level:
    root: DEBUG

server:
  port: 8000
#  ssl:
#    enabled: true
#    client-auth: need
#    key-store: classpath:certs//keystore.p12
#    key-store-password: svn4ever
#    key-store-type: PKCS12

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    registry-fetch-interval-seconds: 10
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10

hystrix:
  command:
    zuul-service:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 100000

zuul-service:
  ribbon:
    ReadTimeout: 5000
    ConnectTimeout: 3000
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 2
    MaxAutoRetries: 2

ribbon:
#  OkToRetryOnAllOperations: true
#  IsSecure: true
#  ReadTimeout: 5000000
#  ConnectTimeout: 5000000
#  MaxAutoRetries: 3
#  MaxAutoRetriesNextServer: 3
#  CustomSSLSocketFactoryClassName: com.netflix.http4.ssl.AcceptAllSocketFactory
#  IsHostnameValidationRequired: false
#  TrustStore: classpath:certs//keystore.p12
#  TrustStorePassword : svn4ever
  eureka:
    enabled: true

zuul:
  ignored-services: '*'
  retryable: true
  host:
    max-total-connections: 100
    max-per-route-connections: 100
  routes:
    zuul-service:
      path: /api/**
      sensitive-headers: null
      service-id: zuul-service
      strip-prefix: false
#      ssl-hostname-validation-enabled: false

endpoints:
  actuator:
    enabled: true
    sensitive: true
  health:
    enabled: true
    sensitive: true
  metrics:
    enabled: true
    id: metrics
    sensitive: true
management:
  security:
    enabled: false