info:
  name: ${project.name}
  version: ${project.version}
  description: ${project.description}

spring:
  application:
    name: zuul-service

logging:
  level:
    root: INFO

server:
  port: 0

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    lease-renewal-interval-in-seconds: 10
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
