# Common properties for all servers: Place common properties in this file to remove duplicity and easy management from one place

logging:
  level:
    root: INFO

endpoints:
  actuator:
    enabled: true
    sensitive: true
  health:
    enabled: true
    sensitive: true
  metrics:
    enabled: true
    id: metrics
    sensitive: true
management:
  security:
    enabled: false