server:
  port: 0

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    lease:
      duration: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 20
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  security:
    enabled: false
